src/main/java/com/example/jeedemo/domain/Device.java
package com.example.jeedemo.domain;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.validation.constraints.Size;

@Entity
@NamedQueries({ 
	@NamedQuery(name = "device.all", query = "Select d from Device d")
})
public class Device {

	private Long id;

	private String name = "";

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@Size(min = 2, max = 20)
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
}

src/main/java/com/example/jeedemo/domain/Specialization.java
package com.example.jeedemo.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@Entity
@NamedQueries({ 
@NamedQuery(name = "specialization.all", query = "Select s from Specialization s"),
@NamedQuery(name = "specialization.unspec", query = "Select s from Specialization s where s.spec = false")
})
public class Specialization {
	
	private Long id;
	private String name;
	private Boolean spec = false;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Boolean getSpec() {
		return spec;
	}
	public void setSpec(Boolean spec) {
		this.spec = spec;
	}
}

src/main/java/com/example/jeedemo/domain/Worker.java
package com.example.jeedemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

@Entity
@NamedQueries({ 
	@NamedQuery(name = "worker.all", query = "Select w from Worker w")
})
public class Worker {

	private Long id;

	private String firstName = "";
	private String lastName = "";
	private String pesel = "";
	private Date registrationDate = new Date();
	private String street = "";
	private String postcode = "";
	private String city = "";
	
	private List<Specialization> specializations = new ArrayList<Specialization>();

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@Size(min = 2, max = 20)
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@Size(min = 2, max = 20)
	public String getLastName() {
		return lastName;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	@Size(min = 2, max = 11)
	public String getPesel() {
		return pesel;
	}
	
	public void setPesel(String pesel) {
		this.pesel = pesel;
	}
	
	@Size(min = 2, max = 20)
	public String getStreet() {
		return street;
	}
	
	public void setStreet(String street) {
		this.street = street;
	}
	
	@Size(min = 2, max = 20)
	public String getPostcode() {
		return postcode;
	}
	
	
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}
	
	@Size(min = 2, max = 20)
	public String getCity() {
		return city;
	}
	
	public void setCity(String city) {
		this.city = city;
	}
	
	@Temporal(TemporalType.DATE)
	public Date getRegistrationDate() {
		return registrationDate;
	}
	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}
	
	// Be careful here, both with lazy and eager fetch type
		@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
		public List<Specialization> getSpecializations() {
			return specializations;
		}
		public void setSpecializations(List<Specialization> specializations) {
			this.specializations = specializations;
		}
}

src/main/java/com/example/jeedemo/web/DeviceFormBean.java
package com.example.jeedemo.web;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jeedemo.domain.Device;
import com.example.jeedemo.service.DeviceManager;

@SessionScoped
@Named("deviceBean")
public class DeviceFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Device device = new Device();
	private ListDataModel<Device> devices = new ListDataModel<Device>();

	@Inject
	private DeviceManager dm;

	public Device getDevice() {
		return device;
	}
	public void setWorker(Device device) {
		this.device = device;
	}
	
	public ListDataModel<Device> getAllDevices() {
		devices.setWrappedData(dm.getAllDevices());
		return devices;
	}
	
	// Actions
	public String addDevice() {
		dm.addDevice(device);
		return "showDevices";
		//return null;
	}

	public String deleteDevice() {
		Device deviceToDelete = devices.getRowData();
		dm.deleteDevice(deviceToDelete);
		return null;
	}

}

src/main/java/com/example/jeedemo/web/SpecFormBean.java
package com.example.jeedemo.web;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jeedemo.domain.Specialization;
import com.example.jeedemo.domain.Worker;
import com.example.jeedemo.service.SpecManager;
import com.example.jeedemo.service.WorkerManager;

@SessionScoped
@Named("specBean")
public class SpecFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private SpecManager sm;

	@Inject
	private WorkerManager wm;

	private Long specializationId;
	private Long workerId;
	
	public Long getSpecializationId() {
		return specializationId;
	}
	public void setSpecializationId(Long specializationId) {
		this.specializationId = specializationId;
	}
	public Long getWorkerId() {
		return workerId;
	}
	public void setWorkerId(Long workerId) {
		this.workerId = workerId;
	}

	public List<Specialization> getAvailableSpecializations() {
		return sm.getAvailableSpecializations();
	}

	public List<Worker> getAllWorkers() {
		return wm.getAllWorkers();
	}

	public String goSpec() {
		sm.goSpec(workerId, specializationId);
		return null;
	}
}

src/main/java/com/example/jeedemo/web/SpecializationFormBean.java
package com.example.jeedemo.web;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jeedemo.domain.Specialization;
import com.example.jeedemo.service.SpecializationManager;

@SessionScoped
@Named("specializationBean")
public class SpecializationFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Specialization specialization = new Specialization();
	private ListDataModel<Specialization> specializations = new ListDataModel<Specialization>();


	@Inject
	private SpecializationManager sm;

	public Specialization getSpecialization() {
		return specialization;
	}
	public void setSpecialization(Specialization specialization) {
		this.specialization = specialization;
	}
	
	public ListDataModel<Specialization> getAllSpecializations() {
		specializations.setWrappedData(sm.getAllSpecializations());
		return specializations;
	}
	
	// Actions
	public String addSpecialization() {
		sm.addSpecialization(specialization);
		return "showSpecializations";
		//return null;
	}

	public String deleteSpecialization() {
		Specialization specializationToDelete = specializations.getRowData();
		sm.deleteSpecialization(specializationToDelete);
		return null;
	}
}

src/main/java/com/example/jeedemo/web/WorkerFormBean.java
package com.example.jeedemo.web;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jeedemo.domain.Specialization;
import com.example.jeedemo.domain.Worker;
import com.example.jeedemo.service.SpecManager;
import com.example.jeedemo.service.WorkerManager;

@SessionScoped
@Named("workerBean")
public class WorkerFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Worker worker = new Worker();
	private ListDataModel<Worker> workers = new ListDataModel<Worker>();

	private Worker workerToShow = new Worker();
    private ListDataModel<Specialization> ownedSpecializations = new ListDataModel<Specialization>();

	@Inject
	private WorkerManager wm;
	
	@Inject
    private SpecManager sm;

	public Worker getWorker() {
		return worker;
	}
	public void setWorker(Worker worker) {
		this.worker = worker;
	}
	
	public ListDataModel<Worker> getAllWorkers() {
		workers.setWrappedData(wm.getAllWorkers());
		return workers;
	}
	
	public ListDataModel<Specialization> getOwnedSpecializations() {
        ownedSpecializations.setWrappedData(wm.getOwnedSpecializations(workerToShow));
        return ownedSpecializations;
}
	
	// Actions
	public String addWorker() {
		wm.addWorker(worker);
		return "showWorkers";
		//return null;
	}

	public String deleteWorker() {
		Worker workerToDelete = workers.getRowData();
		wm.deleteWorker(workerToDelete);
		return null;
	}
	
	public String showDetails() {
	        workerToShow = workers.getRowData();
	        return "details";
	}
	
	public String disposeSpecialization(){
	        Specialization specializationToDispose = ownedSpecializations.getRowData();
	        sm.disposeSpecialization(workerToShow, specializationToDispose);
	        return null;
	}

}

src/main/webapp/addDevice.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="deviceForm">
			<h:outputText value="#{msg.deviceAddLabel}" style="font-weight:bold;"/>
			<table>
			<tr>
				<td><h:outputText value="#{msgdeviceNameLabel}" /></td>
				<td><h:inputText id="name" value="#{deviceBean.device.name}"
					required="#{true}" /></td>
			</tr>
			</table>
			<h:commandButton value="#{msg.deviceFormOKButton}"
				action="#{deviceBean.addDevice}" />

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/addSpecialization.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="specializationForm">
			<h:outputText value="#{msg.specializationAddLabel}" style="font-weight:bold;"/>
			<table>
			<tr>
				<td><h:outputText value="#{msg.specializationNameLabel}" /></td>
				<td><h:inputText id="name" value="#{specializationBean.specialization.name}"
					required="#{true}" /></td>
			</tr>
			</table>
			<h:commandButton value="#{msg.specializationFormOKButton}"
				action="#{specializationBean.addSpecialization}" />

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/addWorker.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="workerForm">
			<h:outputText value="#{msg.workerAddLabel}" style="font-weight:bold;"/>
			<table>
			<tr>
				<td><h:outputText value="#{msg.workerFirstNameLabel}" /></td>
				<td><h:inputText id="firstName" value="#{workerBean.worker.firstName}"
					required="#{true}" /></td>
			</tr>
			<tr>
				<td><h:outputText value="#{msg.workerLastNameLabel}" /></td>
				<td><h:inputText id="lastName" value="#{workerBean.worker.lastName}"
					required="#{true}" /></td>
			</tr>
			<tr>
				<td><h:outputText value="#{msg.workerPeselLabel}" /></td>
				<td><h:inputText id="pin" value="#{workerBean.worker.pesel}" /></td>
			</tr>
			<tr>
				<td><h:outputText value="Registration date" /></td>
				<td><rich:calendar value="#{workerBean.worker.registrationDate}"
					id="calendar" datePattern="dd.MM.yyyy" showApplyButton="#{true}"
					style="width:200px">
				</rich:calendar></td>
			</tr>
			<tr>
				<td><h:outputText value="#{msg.workerStreetLabel}" /></td>
				<td><h:inputText id="street" value="#{workerBean.worker.street}"
					required="#{true}" /></td>
			</tr>
			<tr>
				<td><h:outputText value="#{msg.workerPostCodeLabel}" /></td>
				<td><h:inputText id="postcode" value="#{workerBean.worker.postcode}"
					required="#{true}" /></td>
			</tr>
			<tr>
				<td><h:outputText value="#{msg.workerCityLabel}" /></td>
				<td><h:inputText id="city" value="#{workerBean.worker.city}"
					required="#{true}" /></td>
			</tr>
			</table>
			<h:commandButton value="#{msg.workerFormOKButton}"
				action="#{workerBean.addWorker}" />

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/details.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{workerBean.ownedSpecializations}" var="item">
				<f:facet name="header">Nadane Specjalizacje</f:facet>
				<h:column>
					<f:facet name="header">Nazwa</f:facet>
					<h:outputText value="#{item.name}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.action}</f:facet>
					<h:commandLink value="#{msg.actionDelete}"
						action="#{workerBean.disposeSpecialization}" />
				</h:column>

			</h:dataTable>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<p>#{msg.applicationInfo}</p>
	</ui:define>
</ui:composition>

src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

src/main/webapp/showDevices.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{deviceBean.allDevices}" var="item">
				<f:facet name="header">#{msg.deviceAllLabel}</f:facet>
				<h:column>
					<f:facet name="header">#{msg.deviceNameLabel}</f:facet>
					<h:outputText value="#{item.name}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.action}</f:facet>
					<h:commandLink value="#{msg.actionDelete}"
						action="#{deviceBean.deleteDevice}" />
				</h:column>

			</h:dataTable>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/showSpecializations.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{specializationBean.allSpecializations}" var="item">
				<f:facet name="header">#{msg.specializationAllLabel}</f:facet>
				<h:column>
					<f:facet name="header">#{msg.specializationNameLabel}</f:facet>
					<h:outputText value="#{item.name}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.action}</f:facet>
					<h:commandLink value="#{msg.actionDelete}"
						action="#{specializationBean.deleteSpecialization}" />
				</h:column>

			</h:dataTable>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/showWorkers.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{workerBean.allWorkers}" var="item">
				<f:facet name="header">#{msg.workerAllLabel}</f:facet>
				<h:column>
					<f:facet name="header">#{msg.workerFirstNameLabel}</f:facet>
					<h:outputText value="#{item.firstName}"/>
				</h:column>
				<h:column>
					<f:facet name="header">#{msg.workerLastNameLabel}</f:facet>
					<h:outputText value="#{item.lastName}" />
				</h:column>
				<h:column>
					<f:facet name="header">#{msg.workerPeselLabel}</f:facet>
					<h:outputText value="#{item.pesel}" />
				</h:column>
				<h:column>
					<f:facet name="header">#{msg.workerStreetLabel}</f:facet>
					<h:outputText value="#{item.street}" />
				</h:column>
				<h:column>
					<f:facet name="header">#{msg.workerPostCodeLabel}</f:facet>
					<h:outputText value="#{item.postcode}" />
				</h:column>
				<h:column>
					<f:facet name="header">#{msg.workerCityLabel}</f:facet>
					<h:outputText value="#{item.city}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.action}</f:facet>
                    <h:commandLink value="#{msg.actionDelete}"
                            action="#{workerBean.deleteWorker}" />
                    <h:commandLink value=" Details " action="#{workerBean.showDetails}"/>
                </h:column>

			</h:dataTable>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/spec.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="workerForm">
			<h:panelGrid columns="2">

				<h:outputText value="Pracownik " />
				<h:selectOneMenu value="#{specBean.workerId}">
					<f:selectItems value="#{specBean.allWorkers}" var="worker"
						itemValue="#{worker.id}" itemLabel="#{worker.lastName}" />
				</h:selectOneMenu>

				<h:outputText value="Specializacje" />
				<h:selectOneMenu value="#{specBean.specializationId}">
					<f:selectItems value="#{specBean.availableSpecializations}" var="specialization"
						itemValue="#{specialization.id}" itemLabel="#{specialization.name}" />
				</h:selectOneMenu>


			</h:panelGrid>

			<h:commandButton value="Nadaj" action="#{specBean.goSpec}" />

			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>